/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ClerkIssuer": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkPublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseURL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GenerateMessageResponseQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OpenAIAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PineconeAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}