/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "API": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CLERK_ISSUER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERK_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERK_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GenerateChatTitleQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GenerateMessageResponseQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Realtime": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "Web": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
